### PR TITLE
StmRtc clock - ability to chose clock source and date format 

### PR DESCRIPTION
**Pull request by arkhipenko**
Added ability to specify RTC clock source and date format.

### CODE REVIEW

**Comment by arkhipenko** [comment]
Sorry if the PR is a bit messy - trying to sync up with upstream and introduce changes **after** I made changes... :(

**Comment by bxparks** [comment]
Sorry I can't diff this properly because the files are encoded in DOS format (...except for the last line, which is UNIX encoded, so it's not even a pure DOS format). The diff shows that every line has changed. Can you clean this up, then squash into a single commit?

```
$ git diff origin/develop --stat
 src/AceTime.h                    |   2 +-
 src/ace_time/clock/StmRtcClock.h | 164 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------
 src/ace_time/hw/StmRtc.cpp       | 161 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------
 src/ace_time/hw/StmRtc.h         | 106 +++++++++++++++++++++++++++++++++++++++--------------------------------------
 4 files changed, 223 insertions(+), 210 deletions(-)
```

**Comment by arkhipenko** [comment]
I only changed 3 files - the very last commit should be indicative of the change:

https://github.com/bxparks/AceTime/pull/47/commits/736de6c05216f5d2a0cff0bb1f73dcfc52991381

**Comment by bxparks** [comment]
Hi, Just wondering about the status of this PR. I'm happy to incorporate your fixes or features... if I can diff what they are. :-) I just released v1.6, so please rebase off the latest `develop` branch. I don't expect many conflicts between my commits and your PR.

**Comment by arkhipenko** [comment]
Hi, before I embark on rebasing - any tips on how to avoid the CR/LF disaster? 
Are there git settings I need to change? Should I do it explicitly in Linux?
Thank you.

**Pull request closed without merging**
